import Link from "next/link";
import { AlertTriangle, Filter, MapPin } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

type Order = { id: string; client: string | null; borrower: string | null; property_address: string | null; amc: string | null; status: string; priority: string | null; due_date: string | null; fee_amount: number | null; progress: number | null; warning?: string | null };

function statusLabel(status: string) { return status.replaceAll("_", " ").replace(/\b\w/g, c => c.toUpperCase()); }
function StatusPill({ status }: { status: string }) { const critical = status.includes("hold"); return <span className={`rounded-full border px-3 py-1 text-xs font-medium ${critical ? "border-rose-200 bg-rose-50 text-rose-700" : "border-sky-200 bg-sky-50 text-sky-700"}`}>{statusLabel(status)}</span>; }

export function OrderPipeline({ orders }: { orders: Order[] }) {
  return <Card><CardContent className="p-0"><div className="flex items-center justify-between border-b border-slate-200 p-5"><div><h3 className="font-semibold">Live order pipeline</h3><p className="text-sm text-slate-500">Orders, portal submissions, XML reviews, and exception handling in one place.</p></div><Button variant="outline"><Link href="/orders/open" className="flex items-center"><Filter size={16} className="mr-2"/>View Open</Link></Button></div><div className="divide-y divide-slate-100">{orders.map(order => <div key={order.id} className="p-5 hover:bg-slate-50"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="space-y-2"><div className="flex flex-wrap items-center gap-2"><Link href={`/orders/${order.id}`} className="font-semibold text-blue-700 hover:underline">{order.id}</Link><StatusPill status={order.status}/>{order.priority !== "Normal" && <span className="rounded-full bg-rose-50 px-3 py-1 text-xs font-medium text-rose-700">{order.priority}</span>}</div><p className="text-sm text-slate-600">{order.client} · {order.amc}</p><p className="flex items-center gap-2 text-sm text-slate-500"><MapPin size={15}/>{order.property_address}</p></div><div className="min-w-52 space-y-2"><div className="flex justify-between text-xs text-slate-500"><span>Progress</span><span>{order.progress ?? 0}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-slate-950" style={{ width: `${order.progress ?? 0}%` }}/></div><div className="flex justify-between text-xs text-slate-500"><span>{order.due_date}</span><span>${order.fee_amount}</span></div></div></div>{order.warning && <div className="mt-3 flex items-center gap-2 rounded-xl bg-amber-50 px-3 py-2 text-sm text-amber-800"><AlertTriangle size={16}/>{order.warning}</div>}</div>)}</div></CardContent></Card>;
}
