import Link from "next/link";
import { addDocumentRecord, addOrderNote, updateOrder } from "@/lib/actions/orders";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { AlertTriangle, CalendarDays, DollarSign, FileText, History, Mail, MapPin, NotebookPen, Phone, Save, Upload, UserRound } from "lucide-react";

type Order = Record<string, any>;
type Note = { id: string; body: string; visibility: string; created_at: string; profiles?: { full_name?: string | null } | null };
type HistoryRow = { id: string; status: string; message: string; created_at: string; profiles?: { full_name?: string | null } | null };
type Doc = { id: string; filename: string; document_type: string; visibility: string; created_at: string };
type Finding = { id: string; severity: string; rule_name: string; detail: string; status: string };

const statuses = ["new","assigned","inspection_scheduled","inspection_complete","report_uploaded","review_hold","revision_requested","portal_ready","delivered","completed","cancelled"];
const priorities = ["Normal","Rush","High","On Hold"];
function money(value?: number | null) { return typeof value === "number" ? `$${value.toFixed(2)}` : "$0.00"; }
function statusLabel(value: string) { return value?.replaceAll("_", " ").replace(/\b\w/g, c => c.toUpperCase()) ?? "New"; }
function Field({ label, name, defaultValue, type = "text" }: { label: string; name: string; defaultValue?: any; type?: string }) {
  return <label className="block"><span className="text-xs font-medium text-slate-500">{label}</span><input name={name} type={type} defaultValue={defaultValue ?? ""} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm outline-none focus:border-slate-400"/></label>;
}
function InfoRow({ label, value }: { label: string; value?: React.ReactNode }) { return <div className="flex justify-between gap-4 border-b border-slate-100 py-2 text-sm"><span className="text-slate-500">{label}</span><span className="text-right font-medium text-slate-900">{value || "—"}</span></div>; }

export function OrderDetail({ order, notes, history, documents, findings, message, error }: { order: Order; notes: Note[]; history: HistoryRow[]; documents: Doc[]; findings: Finding[]; message?: string; error?: string }) {
  return <div className="space-y-6">
    <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
      <div>
        <div className="flex flex-wrap items-center gap-2"><Link href="/orders/open" className="text-sm font-medium text-slate-500 hover:text-slate-950">← Open Orders</Link><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-medium text-slate-600">{statusLabel(order.status)}</span>{order.priority && <span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-medium text-amber-700">{order.priority}</span>}</div>
        <h1 className="mt-2 text-3xl font-semibold tracking-tight">{order.id}</h1>
        <p className="mt-1 flex items-center gap-2 text-sm text-slate-500"><MapPin size={15}/>{order.property_address}{order.city ? `, ${order.city}` : ""}{order.state ? `, ${order.state}` : ""}</p>
      </div>
      <div className="flex flex-wrap gap-2"><Button variant="outline"><FileText size={16} className="mr-2"/>Print Details</Button><Button variant="outline"><Mail size={16} className="mr-2"/>Email Appraiser</Button><Button variant="outline">Download XML</Button></div>
    </div>
    {message && <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">Saved successfully.</div>}
    {error && <div className="rounded-2xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}

    <div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]">
      <form action={updateOrder} className="space-y-6">
        <input type="hidden" name="id" value={order.id}/>
        <Card><CardContent className="p-0"><SectionTitle title="Reference Information"/><div className="grid gap-4 p-5 md:grid-cols-4"><Field label="File #" name="id" defaultValue={order.id}/><Field label="Loan #" name="loan_number"/><Field label="Tracking #" name="tracking_number" defaultValue={order.id}/><Field label="FHA #" name="fha_number"/><label className="block"><span className="text-xs font-medium text-slate-500">Status</span><select name="status" defaultValue={order.status} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm">{statuses.map(s => <option key={s} value={s}>{statusLabel(s)}</option>)}</select></label><label className="block"><span className="text-xs font-medium text-slate-500">Priority</span><select name="priority" defaultValue={order.priority ?? "Normal"} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm">{priorities.map(p => <option key={p}>{p}</option>)}</select></label><Field label="Due date" name="due_date" defaultValue={order.due_date}/><Field label="Progress %" name="progress" type="number" defaultValue={order.progress ?? 0}/></div></CardContent></Card>
        <Card><CardContent className="p-0"><SectionTitle title="Client + Borrower Info"/><div className="grid gap-4 p-5 md:grid-cols-3"><Field label="Client" name="client" defaultValue={order.client}/><Field label="Client User / Ordered By" name="client_user" defaultValue={order.client_user}/><Field label="AMC / Portal" name="amc" defaultValue={order.amc}/><Field label="Borrower" name="borrower" defaultValue={order.borrower}/><Field label="Contact Name" name="contact_name" defaultValue={order.contact_name}/><Field label="Contact Phone" name="contact_phone" defaultValue={order.contact_phone}/><Field label="Contact Email" name="contact_email" defaultValue={order.contact_email}/><Field label="Warning / blocker" name="warning" defaultValue={order.warning}/></div></CardContent></Card>
        <Card><CardContent className="p-0"><SectionTitle title="Subject Property + Assignment Info"/><div className="grid gap-4 p-5 md:grid-cols-4"><Field label="Address" name="property_address" defaultValue={order.property_address}/><Field label="City" name="city" defaultValue={order.city}/><Field label="State" name="state" defaultValue={order.state}/><Field label="Zip" name="zip" defaultValue={order.zip}/><Field label="County" name="county" defaultValue={order.county}/><Field label="Product" name="product" defaultValue={order.product}/><Field label="Loan Type" name="loan_type" defaultValue={order.loan_type}/><Field label="Intended Use" name="intended_use" defaultValue={order.intended_use}/><Field label="Occupancy" name="occupancy" defaultValue={order.occupancy}/><Field label="Sale Price" name="sale_price" defaultValue={order.sale_price}/><Field label="Date Needed" name="date_needed" defaultValue={order.date_needed}/><Field label="Inspection Scheduled" name="inspection_scheduled_at" defaultValue={order.inspection_scheduled_at}/></div></CardContent></Card>
        <Card><CardContent className="p-0"><SectionTitle title="Billing + Vendor Info"/><div className="grid gap-4 p-5 md:grid-cols-4"><Field label="Amount to be Billed" name="fee_amount" defaultValue={order.fee_amount}/><Field label="Tech Fee" name="tech_fee_amount" defaultValue={order.tech_fee_amount}/><Field label="Appraiser Fee" name="appraiser_fee" defaultValue={order.appraiser_fee}/><Field label="History message" name="history_message" defaultValue="Order updated."/></div><div className="grid gap-3 p-5 pt-0 md:grid-cols-3"><InfoRow label="Client Balance" value={money(order.fee_amount)}/><InfoRow label="Appraiser Balance" value={money(order.appraiser_fee)}/><InfoRow label="Date Paid" value="Not Paid"/></div></CardContent></Card>
        <Card><CardContent className="p-0"><SectionTitle title="Office Notes + Current Status"/><div className="grid gap-4 p-5"><label><span className="text-xs font-medium text-slate-500">Current Status</span><textarea name="current_status" defaultValue={order.current_status ?? ""} rows={3} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm"/></label><label><span className="text-xs font-medium text-slate-500">Office Notes / Special Instructions</span><textarea name="notes" defaultValue={order.notes ?? ""} rows={5} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm"/></label><Button className="w-fit"><Save size={16} className="mr-2"/>Save Order Changes</Button></div></CardContent></Card>
      </form>

      <div className="space-y-6">
        <Card><CardContent><h3 className="flex items-center gap-2 font-semibold"><NotebookPen size={18}/> Add Note</h3><form action={addOrderNote} className="mt-4 space-y-3"><input type="hidden" name="order_id" value={order.id}/><input type="hidden" name="status" value={order.status}/><textarea name="body" rows={4} placeholder="Type internal order note, appraiser update, or revision comment..." className="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm" required/><select name="visibility" className="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm"><option value="internal">Internal only</option><option value="assigned_appraiser">Assigned appraiser</option><option value="lender_client">Lender/client visible</option><option value="accounting">Accounting</option></select><Button>Add Note</Button></form></CardContent></Card>
        <Card><CardContent><h3 className="flex items-center gap-2 font-semibold"><Upload size={18}/> Add Document Record</h3><form action={addDocumentRecord} className="mt-4 space-y-3"><input type="hidden" name="order_id" value={order.id}/><input name="filename" placeholder="purchase_contract.pdf" className="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm" required/><select name="document_type" className="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm"><option>Purchase Contract</option><option>Engagement Letter</option><option>Appraisal PDF</option><option>XML Report</option><option>Invoice</option><option>Other</option></select><select name="visibility" className="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm"><option value="internal">Internal</option><option value="assigned_appraiser">Assigned appraiser</option><option value="lender_client">Lender/client</option><option value="reviewer">Reviewer</option></select><Button variant="outline">Attach Document</Button></form></CardContent></Card>
        <Card><CardContent><h3 className="flex items-center gap-2 font-semibold"><AlertTriangle size={18}/> Review Findings</h3><div className="mt-4 space-y-3">{findings.length ? findings.map(f => <div key={f.id} className="rounded-2xl border border-slate-200 p-3"><p className="text-sm font-medium">{f.rule_name}</p><p className="mt-1 text-xs text-slate-500">{f.severity.toUpperCase()} · {f.detail}</p></div>) : <p className="text-sm text-slate-500">No open review findings.</p>}</div></CardContent></Card>
      </div>
    </div>

    <div className="grid gap-6 xl:grid-cols-3">
      <Card><CardContent><h3 className="flex items-center gap-2 font-semibold"><History size={18}/> Status History</h3><div className="mt-4 space-y-3">{history.map(h => <div key={h.id} className="rounded-2xl border border-slate-200 p-3"><p className="text-xs text-slate-500">{new Date(h.created_at).toLocaleString()} · {statusLabel(h.status)}</p><p className="mt-1 text-sm">{h.message}</p></div>)}</div></CardContent></Card>
      <Card><CardContent><h3 className="flex items-center gap-2 font-semibold"><NotebookPen size={18}/> Notes</h3><div className="mt-4 space-y-3">{notes.map(n => <div key={n.id} className="rounded-2xl border border-slate-200 p-3"><p className="text-xs text-slate-500">{new Date(n.created_at).toLocaleString()} · {n.visibility}</p><p className="mt-1 text-sm whitespace-pre-wrap">{n.body}</p></div>)}</div></CardContent></Card>
      <Card><CardContent><h3 className="flex items-center gap-2 font-semibold"><FileText size={18}/> Documents</h3><div className="mt-4 space-y-3">{documents.length ? documents.map(d => <div key={d.id} className="rounded-2xl border border-slate-200 p-3"><p className="text-sm font-medium">{d.filename}</p><p className="mt-1 text-xs text-slate-500">{d.document_type} · {d.visibility}</p></div>) : <p className="text-sm text-slate-500">No documents attached yet.</p>}</div></CardContent></Card>
    </div>
  </div>;
}
function SectionTitle({ title }: { title: string }) { return <div className="border-b border-slate-200 bg-slate-100 px-5 py-2 text-sm font-semibold text-slate-700">{title}</div>; }
