import { DollarSign, ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { Metric } from "@/components/dashboard/metric";
import { Card, CardContent } from "@/components/ui/card";

export const metadata = { title: "Accounting and Appraiser Payouts", description: "Track appraisal fees, appraiser payouts, receivables, invoices, and profitability." };
const widgets = [['Accounts receivable','$184,200 outstanding'],['Pending appraiser payouts','$42,880 scheduled'],['AMC billing reconciliation','7 invoices need review'],['Turn-time profitability','Rush files trending +12% margin']];
const permissions = [['Administrator','Full company access including accounting, billing, payouts, user permissions, automation, and audit logs'],['Operations Manager','Manage orders, assignments, review queues, and vendor workflows'],['Appraiser Manager','See/manage appraisers within their own company or branch'],['Staff Appraiser','Access only assigned orders, uploads, revisions, and messages'],['Reviewer','Access review queues and QC findings but not accounting'],['Accounting','Access invoices, fees, payouts, receivables, vendor billing, and reporting'],['Vendor Client','Place orders, upload docs, and track only their company orders']];
export default function AccountingPage() { return <AppShell title="Accounting + Payouts"><div className="space-y-6"><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{widgets.map(([label,value]) => <Metric key={label} icon={DollarSign} label={label} value={value} helper="Live financial tracking"/>)}</section><div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><Card><CardContent><h3 className="font-semibold">Accounting + payout center</h3><div className="mt-4 space-y-3">{[['Appraiser payouts','Track split fees, panel payouts, and payment status'],['Vendor invoicing','Generate invoices for AMC and lender clients'],['Order profitability','Track margin per order and per client'],['Aging receivables','Monitor unpaid invoices and outstanding balances']].map(([a,b]) => <div key={a} className="rounded-2xl border border-slate-200 p-4"><p className="font-medium">{a}</p><p className="mt-1 text-sm text-slate-500">{b}</p></div>)}</div></CardContent></Card><Card><CardContent><h3 className="flex items-center gap-2 font-semibold"><ShieldCheck size={18}/> Role-based access</h3><div className="mt-4 space-y-3">{permissions.map(([role,desc]) => <div key={role} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-3"><p className="font-medium">{role}</p><input type="checkbox" defaultChecked={role === 'Administrator' || role === 'Accounting'} className="h-4 w-4" readOnly/></div><p className="mt-2 text-sm leading-6 text-slate-500">{desc}</p></div>)}</div></CardContent></Card></div></div></AppShell>; }
