import { Bot, Download, ExternalLink, FileText, Upload } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

export const metadata = { title: "PDF Autofill", description: "Upload client order PDFs and map fields to AMC portal submissions." };
const fields = [["Borrower", "Sarah Donnelly", "98%"], ["Property Address", "1248 Haines Ave, Charlotte, NC 28205", "96%"], ["Loan Type", "FHA", "91%"], ["Due Date", "05/28/2026", "93%"], ["Intended Use", "First mortgage refinance", "88%"], ["Contact", "sarah.d@example.com / (704) 555-0188", "82%"]];

export default function OrdersPage() {
  return <AppShell title="PDF + AMC Autofill"><div className="grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><Card><CardContent className="p-6"><h3 className="text-lg font-semibold">Create order from client PDF</h3><p className="mt-1 text-sm text-slate-500">Upload engagement/order PDFs, extract fields, map to AMC portals, and submit with audit history.</p><div className="mt-6 rounded-3xl border-2 border-dashed border-slate-300 bg-slate-50 p-8 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-white shadow-sm"><Upload/></div><p className="mt-4 font-medium">Drop order PDF here</p><p className="mt-1 text-sm text-slate-500">PDF, scanned PDF, lender packet, or email attachment</p><Button className="mt-4">Choose file</Button></div></CardContent></Card><Card><CardContent className="p-6"><div className="mb-4 flex items-center justify-between"><div><h3 className="font-semibold">Extraction review</h3><p className="text-sm text-slate-500">Confirm low-confidence fields before portal submission.</p></div><Bot size={22}/></div><div className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="mb-4 flex items-center gap-2 font-medium"><FileText size={18}/>PDF preview</div><div className="space-y-3"><div className="h-4 w-3/4 rounded bg-slate-200"/><div className="h-4 w-full rounded bg-slate-200"/><div className="h-28 rounded bg-slate-200/70"/></div></div><div className="space-y-3">{fields.map(([label,value,confidence]) => <div key={label} className="rounded-xl border border-slate-200 p-3"><div className="flex items-center justify-between text-xs text-slate-500"><span>{label}</span><span>{confidence}</span></div><input className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm" defaultValue={value}/></div>)}</div></div><div className="mt-5 flex flex-wrap gap-2"><Button><ExternalLink size={16} className="mr-2"/>Launch portal autofill</Button><Button variant="outline"><Download size={16} className="mr-2"/>Export packet</Button></div></CardContent></Card></div></AppShell>;
}
